# =========================
# Server
# =========================
server.address=0.0.0.0
server.port=8080

# =========================
# Supabase
# =========================
supabase.url=https://zfsqitzfjghsrtljsdab.supabase.co
supabase.key=sb_publishable_m5-L44paDQ94Ju95f-YyWw_yIaXWJCt

# =========================
# Admin
# =========================
# .env 의 ADMIN_KEY 환경변수를 우선 사용, 없으면 fallback 값 적용
admin.key=${ADMIN_KEY:a123123!}



# DevTolls ?? ??
spring.devtools.restart.enabled=false

# =========================
# JPA ???? (REST API ?????)-JPA ?? ??? ???? ?? ?
# =========================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration