# =========================
# Server
# =========================
server.port=8080

# =========================
# Supabase
# =========================
supabase.url=https://zfsqitzfjghsrtljsdab.supabase.co
supabase.key=sb_publishable_m5-L44paDQ94Ju95f-YyWw_yIaXWJCt



# DevTolls ?? ??
spring.devtools.restart.enabled=false

# =========================
# JPA ???? (REST API ?????)-JPA ?? ??? ???? ?? ?
# =========================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration